# Generated by Django 6.0.3 on 2026-03-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('posnom', models.CharField(max_length=100, verbose_name='Postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('motdepasse', models.CharField(max_length=100, verbose_name='Mot de passe')),
            ],
        ),
    ]
