# Generated by Django 6.0.3 on 2026-04-17 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='Postnom')),
                ('datenais', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, verbose_name='Numéro de téléphone')),
                ('photo', models.ImageField(default='Profil/default.png', upload_to='Profil/')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
