# Generated by Django 6.0.3 on 2026-03-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='posnom',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nomUt',
            field=models.CharField(default='miradi', max_length=100, verbose_name='nom utilisateur'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='postnom',
            field=models.CharField(default='ndingambote', max_length=100, verbose_name='Postnom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='mengimiradi@gmail.com', max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='motdepasse',
            field=models.CharField(default='Miradi000@', max_length=100, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default='mengi', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero',
            field=models.CharField(default='0901717545', max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default='mengi', max_length=100, verbose_name='Prénom'),
        ),
    ]
