# Generated by Django 6.0.3 on 2026-03-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0002_remove_utilisateur_posnom_utilisateur_nomut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(default='51, Kisantu-Kinshasa, Selembao', max_length=200, verbose_name='Adresse'),
        ),
    ]
