# Generated by Django 6.0.3 on 2026-03-19 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0004_remove_utilisateur_adresse_remove_utilisateur_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('nombre_participants', models.IntegerField(verbose_name='Nombre des participants')),
                ('Date', models.DateField(verbose_name='Date')),
                ('description_de_la_formation', models.CharField(max_length=150, verbose_name='Description de la formation')),
                ('img', models.ImageField(upload_to='formation/', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
