# Generated by Django 6.0.3 on 2026-03-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0005_formation_alter_profil_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formation',
        ),
    ]
