# Generated by Django 6.0.3 on 2026-03-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0006_delete_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='numero',
            field=models.CharField(default='0901717545', max_length=10, verbose_name='Numéro de téléphone'),
        ),
    ]
