# Generated by Django 6.0.3 on 2026-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0007_alter_profil_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='id',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='id',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='nomUt',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='postnom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
        migrations.AddField(
            model_name='profil',
            name='Idprofil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='nom',
            field=models.CharField(default='miradi', max_length=100, verbose_name='nom utilisateur'),
        ),
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.ImageField(default='Profil/default.png', upload_to='Profil/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='postnom',
            field=models.CharField(default='ndingambote', max_length=100, verbose_name='Postnom'),
        ),
        migrations.AddField(
            model_name='profil',
            name='prenom',
            field=models.CharField(default='mengi', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Idutilisateur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='mengimiradi@gmail.com', max_length=254, unique=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='motdepasse',
            field=models.CharField(default='Miradi000@', max_length=150, verbose_name='Mot de passe'),
        ),
    ]
