# Generated by Django 6.0.3 on 2026-03-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('nombre_participants', models.IntegerField(verbose_name='Nombre des participants')),
                ('Date', models.DateField(verbose_name='Date')),
                ('description_de_la_formation', models.CharField(max_length=150, verbose_name='Description de la formation')),
                ('img', models.ImageField(upload_to='formation/', verbose_name='Image')),
            ],
        ),
    ]
