# Generated by Django 6.0.3 on 2026-05-10 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activites',
            fields=[
                ('IdAct', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='Formation', max_length=100, verbose_name='Titre')),
                ('nombre_participants', models.IntegerField(default='30', verbose_name='Nombre des participants')),
                ('date', models.DateField(verbose_name='Date')),
                ('description_de_la_formation', models.CharField(default="formation sur l'évangélisation", max_length=150, verbose_name='Description de la formation')),
                ('img', models.ImageField(blank=True, null=True, upload_to='activites/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Adhérent', 'Adhérent')], default='Ouvrier', max_length=20)),
                ('date_arrivee', models.DateField(default=django.utils.timezone.now, verbose_name='Date arrivée')),
                ('nom_membre', models.CharField(default='Winner', max_length=100, verbose_name='Nom_Membre')),
                ('prenom_membre', models.CharField(default='Alex', max_length=100, verbose_name='Prenom_Membre')),
                ('postnom_membre', models.CharField(default='Miyakudi', max_length=100, verbose_name='Postnom_Membre')),
                ('datenais', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date_naissance')),
                ('numtel', models.CharField(default='0901717545', max_length=20)),
                ('adresse', models.CharField(default='Mfinda, 12,Ngafula, Ngaliema', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/')),
            ],
        ),
        migrations.CreateModel(
            name='versets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='theme')),
                ('personnages_bibliques', models.CharField(max_length=250, verbose_name='personnages_biblique')),
                ('ref_biblic', models.CharField(max_length=100, verbose_name='reference biblique')),
                ('date_publiee', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('IdAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('nomAd', models.CharField(default='miradi', max_length=100, verbose_name='nom utilisateur')),
                ('IdAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestouvriers.activites', verbose_name='Id Activite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_custom', to=settings.AUTH_USER_MODEL)),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestouvriers.membres', verbose_name='Id membre')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestouvriers.versets', verbose_name='Id verset')),
            ],
        ),
    ]
