# Generated by Django 6.0.3 on 2026-03-21 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activites',
            fields=[
                ('IdAct', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='Formation', max_length=100, verbose_name='Titre')),
                ('nombre_participants', models.IntegerField(default='30', verbose_name='Nombre des participants')),
                ('date', models.DateField(verbose_name='Date')),
                ('description_de_la_formation', models.CharField(default="formation sur l'évangélisation", max_length=150, verbose_name='Description de la formation')),
                ('img', models.ImageField(blank=True, default='activites/images_1.webp', null=True, upload_to='activites/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Adhérent', 'Adhérent')], default='Ouvrier', max_length=20)),
                ('date_arrivee', models.DateField(default=django.utils.timezone.now, verbose_name='Date arrivée')),
                ('nom_membre', models.CharField(default='Winner', max_length=100, verbose_name='Nom_Membre')),
                ('prenom_membre', models.CharField(default='Alex', max_length=100, verbose_name='Prenom_Membre')),
                ('postnom_membre', models.CharField(default='Miyakudi', max_length=100, verbose_name='Postnom_Membre')),
                ('datenais', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date_naissance')),
                ('numtel', models.CharField(default='0901717545', max_length=20)),
                ('adresse', models.CharField(default='Mfinda, 12,Ngafula, Ngaliema', max_length=150)),
                ('photo', models.ImageField(blank=True, default='activites/images_1.webp', null=True, upload_to='membres/')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('IdAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('emailAd', models.CharField(default='admin@gmail.com', max_length=150, unique=True)),
                ('mpassAd', models.CharField(default='Miradi000@', max_length=8, unique=True)),
                ('nomAd', models.CharField(default='miradi', max_length=100, verbose_name='nom utilisateur')),
                ('postnomAd', models.CharField(default='ndingambote', max_length=100, verbose_name='Postnom')),
                ('prenomAd', models.CharField(default='mengi', max_length=100, verbose_name='Prénom')),
                ('IdAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestouvriers.activites', verbose_name='Id Activite')),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestouvriers.membres', verbose_name='Id membre')),
            ],
        ),
    ]
