# Generated by Django 6.0.3 on 2026-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestouvriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom et Post-nom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adresse', models.CharField(max_length=150, verbose_name='Adresse physique')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
