# Generated by Django 6.0.3 on 2026-03-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestouvriers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='Date',
            new_name='date',
        ),
    ]
