# Generated by Django 6.0.3 on 2026-03-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestouvriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activites',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='activites/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='membres/'),
        ),
    ]
