# Generated by Django 6.0.3 on 2026-05-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestouvriers', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
