# Generated by Django 6.0.3 on 2026-03-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestouvriers', '0002_alter_activites_img_alter_membres_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='versets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='theme')),
                ('personnages_bibliques', models.CharField(max_length=250, verbose_name='personnages_biblique')),
                ('ref_biblic', models.CharField(verbose_name=50)),
                ('date_publiee', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
