# Generated by Django 6.0.3 on 2026-03-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestouvriers', '0002_rename_date_formation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activites',
            fields=[
                ('IdAct', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='Formation', max_length=100, verbose_name='Titre')),
                ('nombre_participants', models.IntegerField(default='30', verbose_name='Nombre des participants')),
                ('date', models.DateField(verbose_name='Date')),
                ('description_de_la_formation', models.CharField(default="formation sur l'évangélisation", max_length=150, verbose_name='Description de la formation')),
                ('img', models.ImageField(default='activites/images_1.webp', upload_to='activites/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('IdAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('emailAd', models.CharField(default='admin@gmail.com', max_length=150, unique=True)),
                ('mpassAd', models.CharField(default='Miradi000@', max_length=8, unique=True)),
                ('nomAd', models.CharField(default='miradi', max_length=100, verbose_name='nom utilisateur')),
                ('postnomAd', models.CharField(default='ndingambote', max_length=100, verbose_name='Postnom')),
                ('prenomAd', models.CharField(default='mengi', max_length=100, verbose_name='Prénom')),
                ('IdAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestouvriers.activites', verbose_name='Id Activite')),
            ],
        ),
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('IdMembre', models.AutoField(primary_key=True, serialize=False)),
                ('Statut', models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Adhérent', 'Adhérent')], default='Ouvrier', max_length=20)),
                ('Date_arrivee', models.DateField(verbose_name='Date arrivée')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='formation',
        ),
        migrations.AddField(
            model_name='admin',
            name='IdMembre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestouvriers.membres', verbose_name='Id membre'),
        ),
    ]
