# Generated by Django 6.0.3 on 2026-03-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestouvriers', '0003_versets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versets',
            name='description',
            field=models.CharField(max_length=150, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='versets',
            name='ref_biblic',
            field=models.CharField(max_length=100, verbose_name='reference biblique'),
        ),
    ]
